@apiURL=http://localhost:8088
@token={{$dotenv TEMP_TOKEN}}

GET {{apiURL}}/boards
Authorization: Bearer {{token}}

###

POST {{apiURL}}/boards
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Öl"
}
###
POST {{apiURL}}/boards/67078d1ac322546d976359d4/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Sorter",
    "note" : "Pirkka Lager, Aura, Gränges",
    "color": "ff0000",
    "positionT" :  "10px",
    "positionL" : "20px"
}

###
GET {{apiURL}}/boards/67050916700978f4b691606e/notes
Authorization: Bearer {{token}}